version: '3.8'

services:
  backend:
    build:
      context: ./aqm-backend
    #container_name: aqm-backend
    ports:
      - "5005:5005"
    volumes:
      - ./aqm-backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - ./aqm-backend/.env
    depends_on:
      - db
      - ml              
    networks:
      - aqm-net

  frontend:
    build:
      context: ./aqm-frontend
      args:
        - REACT_APP_API_URL=/api
    container_name: aqm-frontend
    ports:
      - "3001:80"
    # volumes:
    #  - ./aqm-frontend:/app
      # - /app/node_modules
    environment:
      - REACT_APP_API_URL=/api
    networks:
      - aqm-net

  ml:
    build:
      context: ./aqm-backend
      dockerfile: Dockerfile.ml
    container_name: aqm-ml
    ports:
      - "8008:8008"          
    volumes:
      - ./aqm-backend:/app
      - /app/node_modules
    networks:
      - aqm-net


  db:
    image: postgres:14
    container_name: aqm-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: blub
      POSTGRES_DB: aqm_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - aqm-net

  # nginx:
  #   image: nginx:1.28
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./aqm-frontend/build:/usr/share/nginx/html
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf\
  #     - ./certs:/etc/nginx/certs
  #   depends_on:
  #     - frontend
  #     - backend
  #   networks:
  #     - aqm-net

volumes:
  postgres_data:

networks:
  aqm-net:
    name: aqm-project_aqm-net
